name: Magnetic.am
description: Magnetic web app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.0+5

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  wonderpush_flutter: ^2.0.0
  wonderpush_fcm_flutter: ^1.0.1
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.0.0
  url_launcher: ^6.1.0
  flutter_launcher_icons: ^0.9.2
  rename: ^2.0.1
  provider: ^6.0.2
  external_app_launcher: ^2.0.2
  # flutter_webview_pro:
  # The package is needed for loading files in WebView via input type file
  # https://github.com/wenzhiming/flutter-plugins/pull/5
  # Remove the custom package with plugins when the changes
  # from the specified pull request are accepted or the specified
  # bugs are fixed. In version 3.0.1 + 2 on iOS, the project does
  # not build due to an outdated dependency.
  flutter_webview_pro:
    path: custom_packages/flutter-plugins/packages/webview_flutter/webview_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

